// Linguagem: Java

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package treino.java04;

/**
 *
 * @author leomarotta
 */
public class Quack extends javax.swing.JFrame {

    /**
     * Creates new form Quack
     */
    public Quack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maiusculaMinuscula = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JTextField = new javax.swing.JPanel();
        Maiuscula = new javax.swing.JRadioButton();
        Minuscula = new javax.swing.JRadioButton();
        tfEntrada = new javax.swing.JTextField();
        JCombo = new javax.swing.JPanel();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        btnMostrar = new javax.swing.JButton();
        lblresultado = new javax.swing.JLabel();
        JTextArea = new javax.swing.JPanel();
        limparAbas = new javax.swing.JPanel();
        btnLimpar = new javax.swing.JButton();
        btnAba1 = new javax.swing.JButton();
        btnAba2 = new javax.swing.JButton();
        btnAba3 = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        menuSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maiusculaMinuscula.add(Maiuscula);
        Maiuscula.setText("Maiuscula");

        maiusculaMinuscula.add(Minuscula);
        Minuscula.setText("Minuscula");

        tfEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfEntradaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout JTextFieldLayout = new javax.swing.GroupLayout(JTextField);
        JTextField.setLayout(JTextFieldLayout);
        JTextFieldLayout.setHorizontalGroup(
            JTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTextFieldLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(JTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfEntrada)
                    .addGroup(JTextFieldLayout.createSequentialGroup()
                        .addComponent(Maiuscula)
                        .addGap(70, 70, 70)
                        .addComponent(Minuscula)))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        JTextFieldLayout.setVerticalGroup(
            JTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JTextFieldLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(JTextFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Maiuscula)
                    .addComponent(Minuscula))
                .addGap(40, 40, 40)
                .addComponent(tfEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("JTextField", JTextField);

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pato", "Panda", "Pterodactil" }));
        combo1.setSelectedItem("");
        combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo1ItemStateChanged(evt);
            }
        });

        btnMostrar.setText("Mostrar Combo");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        lblresultado.setText("O combo formado:");

        javax.swing.GroupLayout JComboLayout = new javax.swing.GroupLayout(JCombo);
        JCombo.setLayout(JComboLayout);
        JComboLayout.setHorizontalGroup(
            JComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JComboLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(JComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combo2, 0, 150, Short.MAX_VALUE))
                .addGap(119, 119, 119)
                .addComponent(lblresultado)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        JComboLayout.setVerticalGroup(
            JComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JComboLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(JComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblresultado))
                .addGap(35, 35, 35)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("JCombo", JCombo);

        javax.swing.GroupLayout JTextAreaLayout = new javax.swing.GroupLayout(JTextArea);
        JTextArea.setLayout(JTextAreaLayout);
        JTextAreaLayout.setHorizontalGroup(
            JTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 789, Short.MAX_VALUE)
        );
        JTextAreaLayout.setVerticalGroup(
            JTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("JTextArea", JTextArea);

        limparAbas.setLayout(new java.awt.GridLayout(1, 0));

        btnLimpar.setText("Limpar");
        btnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimparMouseClicked(evt);
            }
        });
        limparAbas.add(btnLimpar);

        btnAba1.setText("Aba 1");
        btnAba1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAba1MouseClicked(evt);
            }
        });
        limparAbas.add(btnAba1);

        btnAba2.setText("Aba 2");
        btnAba2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAba2MouseClicked(evt);
            }
        });
        limparAbas.add(btnAba2);

        btnAba3.setText("Aba 3");
        btnAba3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAba3MouseClicked(evt);
            }
        });
        limparAbas.add(btnAba3);

        menuArquivo.setText("Arquivo");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuSair);

        menu.add(menuArquivo);

        menuSobre.setText("Sobre");
        menu.add(menuSobre);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(limparAbas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(limparAbas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.out.println("MENU SAIR EVENTO");
        dispose();
    }//GEN-LAST:event_menuSairActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        System.out.println("BTNMOSTRAR EVENTO");
        
        lblresultado.setText(combo2.getSelectedItem().toString());
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void tfEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfEntradaKeyTyped
        System.out.println("TFENTRADA EVENTO");
        char caractereDigitado = evt.getKeyChar();
        if(Maiuscula.isSelected()){
            caractereDigitado = Character.toUpperCase(caractereDigitado);
            System.out.println("Maiuscula");
        }if(Minuscula.isSelected()){
            caractereDigitado = Character.toLowerCase(caractereDigitado);
            System.out.println("Minuscula");
        }
        evt.setKeyChar(caractereDigitado);
    }//GEN-LAST:event_tfEntradaKeyTyped

    private void btnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimparMouseClicked
        tfEntrada.setText("");
    }//GEN-LAST:event_btnLimparMouseClicked

    private void btnAba1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAba1MouseClicked
        int indiceAba = jTabbedPane1.indexOfTab("JTextField");
        if (indiceAba != -1) {
            jTabbedPane1.setSelectedIndex(indiceAba);
        }
    }//GEN-LAST:event_btnAba1MouseClicked

    private void btnAba2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAba2MouseClicked
        int indiceAba = jTabbedPane1.indexOfTab("JCombo");
        if (indiceAba != -1) {
            jTabbedPane1.setSelectedIndex(indiceAba);
        }
    }//GEN-LAST:event_btnAba2MouseClicked

    private void btnAba3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAba3MouseClicked
        int indiceAba = jTabbedPane1.indexOfTab("JTextArea");
        if (indiceAba != -1) {
            jTabbedPane1.setSelectedIndex(indiceAba);
        }
    }//GEN-LAST:event_btnAba3MouseClicked

    private void combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo1ItemStateChanged
        combo2.removeAllItems();
        String itemSelecionado = (String) combo1.getSelectedItem();
        if (itemSelecionado != null) {
            switch (itemSelecionado) {
                case "Pato":
                    combo2.addItem("Pato Cinza");
                    combo2.addItem("Pato Branco");
                    break;
                case "Panda":
                    combo2.addItem("Panda Branco");
                    combo2.addItem("Panda Vermelho");
                    break;
                case "Pterodactil":
                    combo2.addItem("Pterodactil Verde");
                    combo2.addItem("Pterodactil Vermelho");
                    break;
            }
        }
    }//GEN-LAST:event_combo1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quack.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JCombo;
    private javax.swing.JPanel JTextArea;
    private javax.swing.JPanel JTextField;
    private javax.swing.JRadioButton Maiuscula;
    private javax.swing.JRadioButton Minuscula;
    private javax.swing.JButton btnAba1;
    private javax.swing.JButton btnAba2;
    private javax.swing.JButton btnAba3;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JPanel limparAbas;
    private javax.swing.ButtonGroup maiusculaMinuscula;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSobre;
    private javax.swing.JTextField tfEntrada;
    // End of variables declaration//GEN-END:variables
}
